### PR TITLE
added FloatImage interface for feature extractor

### PR DESCRIPTION
**Pull request by ghost**
On our usual way of creating PR's, I forgot that the branch we're using for Theia is the fix that @KindDragon did in the akaze-pthread-fix branch, not in master branch. Hence, I'm creating a new PR to merge the changes I did yesterday to this akaze-pthread-fix, instead of master.

Perhaps we can roll back the changes we made in master since we're not using them anyways, and so our forked master still agrees with the upstream.

Does this make sense?

Change-Id: I4425377988ac15d4b9eb391b163143f83bb2f6a7

### CODE REVIEW

**Comment by Slonegg** [comment]
I've switched Theia to master in conan-packages, so the package should contain changes that you've introduced @rdiazgarHP

**Comment by KindDragon** [comment]
Please don't use branches from the base repository in our forks. It is very easy to introduce in conan package error by updating package `master` branch to another commit

**Comment by Slonegg** [comment]
Okay, we’ll create new branch and use it conan package next time.

**Comment by ghost** [comment]
Then, should we also roll back in our master branch the few commits I added when trying to fix akaze by myself? This way our master would match the base repository.

**Comment by Slonegg** [comment]
I think “proper” workflow when you do changes like these:

1.      Pull master from upstream

2.      Create branch based on latest master and add your changes

3.      Submit a PR to upstream with your changes

4.      Update branch in conan package and rebuild package

But if it works for you for now you can leave it as is and do it properly next time. Also package maintainers often ignore your PRs, so sometimes this proper approach is useless.

**Comment by KindDragon** [comment]
We can do this next time, as Dmitry suggests

**Pull request merged**
